import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Activity, ArrowRight, Bell, CalendarDays, Check, ChevronRight, CirclePlay, Clock3, Dumbbell, Flame, HeartPulse, Home, Leaf, Menu, Search, Settings, Target, Trophy, UserRound, Utensils, Video, X, Apple, MessageCircle, Play, Plus } from "lucide-react";

export const Route = createFileRoute("/")({ component: GymApp });

const navItems = [
  { name: "Visão geral", icon: Home },
  { name: "Treinos", icon: Dumbbell },
  { name: "Nutrição", icon: Leaf },
  { name: "Especialistas", icon: HeartPulse },
  { name: "Progresso", icon: Activity },
  { name: "Meu perfil", icon: UserRound },
];
const exercises = [
  { name: "Agachamento livre", detail: "Pernas · 4 séries × 10 reps", time: "08 min" },
  { name: "Supino com halteres", detail: "Peitoral · 3 séries × 12 reps", time: "07 min" },
  { name: "Remada baixa", detail: "Costas · 3 séries × 12 reps", time: "06 min" },
  { name: "Prancha abdominal", detail: "Core · 3 séries × 45 segundos", time: "04 min" },
];
const meals = [
  { time: "07:30", meal: "Café da manhã", food: "Ovos, pão integral e fruta", kcal: "420 kcal" },
  { time: "12:30", meal: "Almoço", food: "Frango, arroz, feijão e salada", kcal: "610 kcal" },
  { time: "16:00", meal: "Lanche", food: "Iogurte natural com aveia", kcal: "230 kcal" },
  { time: "20:00", meal: "Jantar", food: "Peixe, legumes e batata-doce", kcal: "480 kcal" },
];

function GymApp() {
  const [activeNav, setActiveNav] = useState("Visão geral");
  const [done, setDone] = useState<string[]>(["Supino com halteres"]);
  const [query, setQuery] = useState("");
  const [started, setStarted] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [showVideo, setShowVideo] = useState(false);
  const [goal, setGoal] = useState("Ganhar massa muscular");
  const [water, setWater] = useState(4);
  const filtered = exercises.filter(x => x.name.toLowerCase().includes(query.toLowerCase()));
  const changePage = (page: string) => { setActiveNav(page); setMobileMenu(false); };
  const progress = Math.round(done.length / exercises.length * 100);

  return <div className="gym-app fit-app">
    <aside className={"sidebar " + (mobileMenu ? "sidebar-open" : "")}>
      <a className="gym-logo" href="#inicio" onClick={() => changePage("Visão geral")}><span className="logo-mark"><Dumbbell size={23} strokeWidth={2.5}/></span><span>FITPRO<span className="logo-dot">.</span><small>PERFORMANCE CLUB</small></span></a>
      <div className="side-label">SEU ESPAÇO</div>
      <nav className="side-nav">{navItems.map(({name,icon:Icon})=><button key={name} className={"nav-item "+(activeNav===name?"active":"")} onClick={()=>changePage(name)}><Icon size={18}/>{name}{name==="Treinos"&&<span className="nav-count">4</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="coach-card"><div className="coach-icon"><HeartPulse size={20}/></div><strong>Seu próximo nível.</strong><p>Consistência hoje. Resultados amanhã.</p><button onClick={()=>changePage("Especialistas")}>Falar com especialista <ChevronRight size={15}/></button></div><button className="nav-item settings-item" onClick={()=>changePage("Configurações")}><Settings size={18}/> Configurações</button><div className="user-mini"><div className="avatar">JD</div><div><strong>João Dias</strong><small>Área do aluno</small></div><button aria-label="Abrir perfil" onClick={()=>changePage("Meu perfil")}><ChevronRight size={17}/></button></div></div>
    </aside>
    <main className="main-content" id="inicio">
      <header className="topbar"><button className="fit-mobile-menu icon-button" aria-label="Abrir menu" onClick={()=>setMobileMenu(!mobileMenu)}><Menu size={20}/></button><div className="mobile-brand"><Dumbbell size={20}/> FITPRO<span>.</span></div><div className="breadcrumb">Meu espaço <ChevronRight size={14}/><strong>{activeNav}</strong></div><div className="top-actions"><div className="date-chip"><CalendarDays size={16}/> Quinta-feira, 8 de outubro</div><button className="icon-button" aria-label="Notificações"><Bell size={18}/><i/></button><div className="avatar top-avatar">JD</div></div></header>
      <div className="page-wrap">
        {activeNav==="Visão geral" && <>
          <section className="welcome-row"><div><div className="section-kicker"><span/> SUA JORNADA COMEÇA AQUI</div><h1>Hoje é dia de <span>evoluir.</span></h1><p>Um passo de cada vez. Vamos construir sua melhor versão?</p></div><button className="outline-button" onClick={()=>changePage("Progresso")}><Activity size={17}/> Minha evolução</button></section>
          <section className="fit-hero">
            <video className="fit-hero-video" autoPlay muted loop playsInline preload="metadata" poster="https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=1600"><source src="https://videos.pexels.com/video-files/3195394/3195394-hd_1920_1080_25fps.mp4" type="video/mp4"/></video>
            <div className="fit-hero-shade"/>
            <div className="fit-float fit-float-one"><span className="fit-float-icon"><Flame size={17}/></span><div><b>7 dias</b><small>de consistência</small></div></div>
            <div className="fit-float fit-float-two"><span className="fit-pulse"/><div><b>Seu ritmo.</b><small>Seu progresso.</small></div></div>
            <div className="hero-copy fit-hero-copy"><div className="hero-pill"><Flame size={14}/> TREINO DO DIA</div><h2>Supere seus<br/><span>limites.</span></h2><p>Treino de corpo inteiro para ganhar força, energia e confiança.</p><div className="hero-meta"><span><Clock3 size={16}/> 35 min</span><span><Dumbbell size={16}/> 4 exercícios</span><span><Activity size={16}/> Todos os níveis</span></div><button className="green-button" onClick={()=>{setStarted(true);changePage("Treinos")}}><CirclePlay size={18}/>{started?"Continuar treino":"Começar treino"}<ChevronRight size={17}/></button></div>
            <div className="fit-hero-caption"><Video size={14}/> MOVIMENTO REAL · FOCO TOTAL</div>
          </section>
          <section className="stats-grid"><article className="stat-card"><div className="stat-top"><span>Treinos na semana</span><span className="stat-icon"><Dumbbell size={18}/></span></div><div className="stat-value">04 <small>/ 05</small></div><div className="stat-bottom"><span className="trend">+1 treino</span><span>meta semanal</span></div><div className="mini-progress"><i style={{width:"80%"}}/></div></article><article className="stat-card"><div className="stat-top"><span>Tempo ativo</span><span className="stat-icon"><Clock3 size={18}/></span></div><div className="stat-value">3h 25<small>min</small></div><div className="stat-bottom"><span className="trend">+12%</span><span>esta semana</span></div><div className="mini-progress"><i style={{width:"67%"}}/></div></article><article className="stat-card"><div className="stat-top"><span>Água hoje</span><span className="stat-icon"><Apple size={18}/></span></div><div className="stat-value">{water}<small> / 8 copos</small></div><div className="stat-bottom"><button className="fit-inline-action" onClick={()=>setWater(Math.min(8,water+1))}><Plus size={13}/> Registrar copo</button><span>meta diária</span></div><div className="mini-progress"><i style={{width:(water/8*100)+"%"}}/></div></article><article className="stat-card"><div className="stat-top"><span>Sequência atual</span><span className="stat-icon"><Trophy size={18}/></span></div><div className="stat-value">7 <small>dias</small></div><div className="stat-bottom"><span className="trend">Boa sequência!</span><span>continue assim</span></div><div className="mini-progress"><i style={{width:"74%"}}/></div></article></section>
          <section className="lower-grid"><article className="panel workout-panel"><div className="panel-heading"><div><div className="section-kicker">PLANO DE HOJE</div><h3>Corpo inteiro</h3><p>{done.length} de {exercises.length} exercícios concluídos</p></div><button className="text-button" onClick={()=>changePage("Treinos")}>Ver treino <ChevronRight size={15}/></button></div><div className="workout-progress"><div><span>Progresso do treino</span><strong>{progress}%</strong></div><div className="progress-track"><i style={{width:progress+"%"}}/></div></div><div className="exercise-list">{exercises.slice(0,3).map(x=><button key={x.name} className={"exercise-row "+(done.includes(x.name)?"exercise-done":"")} onClick={()=>setDone(old=>old.includes(x.name)?old.filter(n=>n!==x.name):[...old,x.name])}><span className="exercise-check">{done.includes(x.name)?<Check size={15}/>:<Plus size={15}/>}</span><span className="exercise-info"><strong>{x.name}</strong><small>{x.detail}</small></span><ChevronRight className="exercise-arrow" size={17}/></button>)}</div><button className="start-bottom" onClick={()=>{setStarted(true);changePage("Treinos")}}>{started?"Continuar sessão":"Ver sessão completa"} <ArrowRight size={17}/></button></article>
          <article className="panel nutrition-teaser"><div className="panel-heading"><div><div className="section-kicker">ENERGIA PARA EVOLUIR</div><h3>Nutrição diária</h3><p>Seu resumo alimentar</p></div><span className="nutrition-icon"><Utensils size={19}/></span></div><div className="nutrition-calories"><div><strong>1.240</strong><span>kcal consumidas</span></div><div className="calorie-ring"><span>58%</span></div></div><div className="nutrition-bar"><i/></div><div className="nutrition-macro"><span><i/> Proteínas <b>68g</b></span><span><i/> Carboidratos <b>142g</b></span><span><i/> Gorduras <b>39g</b></span></div><button className="start-bottom" onClick={()=>changePage("Nutrição")}>Abrir meu plano alimentar <ArrowRight size={17}/></button></article></section>
          <section className="fit-specialist-strip"><div className="fit-specialist-icon"><HeartPulse size={24}/></div><div><span className="section-kicker">ACOMPANHAMENTO PROFISSIONAL</span><h3>Você não precisa fazer isso sozinho.</h3><p>Encontre orientação de nutricionistas e personal trainers cadastrados.</p></div><button className="green-button" onClick={()=>changePage("Especialistas")}>Conhecer especialistas <ArrowRight size={16}/></button></section>
        </>}
        {activeNav==="Treinos" && <section className="fit-page-section"><div className="section-kicker"><span/> PLANO DE TREINO</div><h1>Seu treino. <span>Seu progresso.</span></h1><p className="fit-page-intro">Marque cada exercício concluído e acompanhe sua sessão em tempo real.</p><div className="fit-workout-banner"><div><span className="hero-pill"><Flame size={14}/> TREINO A · CORPO INTEIRO</span><h2>{started?"Treino em andamento":"Pronto para começar?"}</h2><p>35 minutos · 4 exercícios · Intensidade moderada</p></div><button className="green-button" onClick={()=>setStarted(!started)}>{started?"Pausar treino": "Iniciar sessão"} <Play size={16}/></button></div><div className="panel fit-exercises-panel"><div className="panel-heading"><div><h3>Lista de exercícios</h3><p>{done.length} de {exercises.length} concluídos · {progress}%</p></div><div className="fit-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar exercício"/></div></div><div className="progress-track"><i style={{width:progress+"%"}}/></div>{filtered.map(x=><button key={x.name} className={"exercise-row "+(done.includes(x.name)?"exercise-done":"")} onClick={()=>setDone(old=>old.includes(x.name)?old.filter(n=>n!==x.name):[...old,x.name])}><span className="exercise-check">{done.includes(x.name)?<Check size={15}/>:<Plus size={15}/>}</span><span className="exercise-info"><strong>{x.name}</strong><small>{x.detail}</small></span><span className="fit-exercise-time">{x.time}</span><ChevronRight size={17}/></button>)}</div></section>}
        {activeNav==="Nutrição" && <section className="fit-page-section"><div className="section-kicker"><span/> NUTRIÇÃO E BEM-ESTAR</div><h1>Coma bem. <span>Viva melhor.</span></h1><p className="fit-page-intro">Organize sua rotina alimentar e acompanhe hábitos. Planos clínicos devem ser definidos por nutricionista.</p><div className="fit-nutrition-layout"><article className="panel fit-food-summary"><div className="section-kicker">RESUMO DE HOJE</div><div className="fit-big-number">1.740 <small>/ 2.200 kcal</small></div><div className="nutrition-bar"><i/></div><div className="fit-food-stats"><span>Proteínas <b>68 / 120g</b></span><span>Carboidratos <b>142 / 250g</b></span><span>Gorduras <b>39 / 70g</b></span></div><div className="fit-water-box"><div><Apple size={19}/><strong>Hidratação</strong><small>{water} de 8 copos registrados</small></div><button className="green-button" onClick={()=>setWater(Math.min(8,water+1))}><Plus size={16}/> Adicionar água</button></div></article><article className="panel"><div className="panel-heading"><div><div className="section-kicker">SUGESTÃO DE ROTINA</div><h3>Refeições do dia</h3></div><Utensils size={20}/></div>{meals.map(m=><div className="fit-meal-row" key={m.time}><span className="fit-meal-time">{m.time}</span><div><strong>{m.meal}</strong><p>{m.food}</p><small>{m.kcal}</small></div><Check size={16}/></div>)}</article></div><div className="fit-note"><HeartPulse size={18}/> <span>Este exemplo é informativo e não substitui avaliação individual de um nutricionista.</span></div></section>}
        {activeNav==="Especialistas" && <section className="fit-page-section"><div className="section-kicker"><span/> TIME DE ESPECIALISTAS</div><h1>Orientação de <span>verdade.</span></h1><p className="fit-page-intro">Encontre profissionais para acompanhar sua jornada. Perfis abaixo são exemplos de apresentação; agendamento real exige cadastro e disponibilidade confirmados.</p><div className="fit-expert-grid"><article className="panel fit-expert-card"><div className="fit-expert-avatar fit-expert-green"><Leaf size={30}/></div><span className="fit-expert-tag">NUTRIÇÃO</span><h3>Nutricionista</h3><p>Planejamento alimentar individualizado, hábitos sustentáveis e acompanhamento.</p><div className="fit-expert-meta"><span><CalendarDays size={15}/> Consulta agendada</span><span><MessageCircle size={15}/> Acompanhamento</span></div><button className="green-button" onClick={()=>setShowVideo(true)}>Como funciona <ArrowRight size={16}/></button></article><article className="panel fit-expert-card"><div className="fit-expert-avatar fit-expert-dark"><Dumbbell size={30}/></div><span className="fit-expert-tag">TREINAMENTO</span><h3>Personal trainer</h3><p>Orientação de técnica, planejamento de exercícios e metas compatíveis com seu nível.</p><div className="fit-expert-meta"><span><CalendarDays size={15}/> Rotina personalizada</span><span><MessageCircle size={15}/> Suporte</span></div><button className="green-button" onClick={()=>setShowVideo(true)}>Como funciona <ArrowRight size={16}/></button></article></div></section>}
        {activeNav==="Progresso" && <section className="fit-page-section"><div className="section-kicker"><span/> SUA EVOLUÇÃO</div><h1>Olhe o quanto <span>já avançou.</span></h1><p className="fit-page-intro">Resumo demonstrativo para acompanhar seus hábitos e consistência.</p><div className="stats-grid"><article className="stat-card"><div className="stat-top"><span>Treinos concluídos</span><span className="stat-icon"><Dumbbell size={18}/></span></div><div className="stat-value">16 <small>este mês</small></div><div className="mini-progress"><i style={{width:"76%"}}/></div></article><article className="stat-card"><div className="stat-top"><span>Tempo ativo</span><span className="stat-icon"><Clock3 size={18}/></span></div><div className="stat-value">12h <small>40min</small></div><div className="mini-progress"><i style={{width:"68%"}}/></div></article><article className="stat-card"><div className="stat-top"><span>Consistência</span><span className="stat-icon"><Trophy size={18}/></span></div><div className="stat-value">82<small>%</small></div><div className="mini-progress"><i style={{width:"82%"}}/></div></article><article className="stat-card"><div className="stat-top"><span>Meta da semana</span><span className="stat-icon"><Target size={18}/></span></div><div className="stat-value">4 <small>/ 5 treinos</small></div><div className="mini-progress"><i style={{width:"80%"}}/></div></article></div><div className="panel fit-goal-panel"><div><div className="section-kicker">SEU OBJETIVO ATUAL</div><h3>{goal}</h3><p>Escolha uma meta para personalizar sua experiência.</p></div><select value={goal} onChange={e=>setGoal(e.target.value)}><option>Ganhar massa muscular</option><option>Perder gordura</option><option>Melhorar condicionamento</option><option>Ter mais saúde e energia</option></select></div></section>}
        {(activeNav==="Meu perfil"||activeNav==="Configurações") && <section className="fit-page-section"><div className="section-kicker"><span/> CONTA E PREFERÊNCIAS</div><h1>Seu espaço, <span>do seu jeito.</span></h1><p className="fit-page-intro">Gerencie suas preferências e o foco da sua jornada fitness.</p><div className="panel fit-profile-panel"><div className="fit-profile-avatar">JD</div><div className="fit-profile-info"><h3>João Dias</h3><p>Perfil de demonstração · aluno FitPro</p><label htmlFor="fit-goal">Meu objetivo principal</label><select id="fit-goal" value={goal} onChange={e=>setGoal(e.target.value)}><option>Ganhar massa muscular</option><option>Perder gordura</option><option>Melhorar condicionamento</option><option>Ter mais saúde e energia</option></select></div></div><div className="fit-note"><Settings size={18}/><span>O perfil exibido é ilustrativo. Para autenticação, sincronização de dados e atendimento, é necessário conectar os serviços reais do projeto.</span></div></section>}
        <footer className="app-footer"><span>© 2026 FITPRO PERFORMANCE CLUB</span><span>Feito para sua melhor versão <span className="footer-heart">♥</span></span></footer>
      </div>
    </main>
    {showVideo&&<div className="modal-backdrop" onClick={()=>setShowVideo(false)}><section className="plan-modal fit-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Fechar" onClick={()=>setShowVideo(false)}><X size={20}/></button><div className="section-kicker">PRÓXIMOS PASSOS</div><h2>Acompanhamento profissional</h2><p className="modal-subtitle">Esta área está preparada para receber perfis verificados, horários disponíveis e contato seguro quando o serviço profissional for conectado.</p><div className="fit-modal-list"><span><Check size={16}/> Perfil e credenciais do profissional</span><span><Check size={16}/> Agenda e disponibilidade</span><span><Check size={16}/> Canal de contato protegido</span></div><button className="green-button modal-done" onClick={()=>setShowVideo(false)}>Entendi <Check size={17}/></button></section></div>}
  </div>;
}
